apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      terminationGracePeriodSeconds: 3
      containers:
      - name: hello-world
        image: local/hello-world:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
          - name: DB_URL 
            value: "${DB_VALUE}"
          - name: WEB_URL 
            value: "http://kouka-web:8080"


