apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-demo
data:
  # 環境変数として利用、Key：Value
  env_key_1: "3"
  env_key_2: "test-value"

  # Mount as File
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  application.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  terminationGracePeriodSeconds: 3
  containers:
    - name: hello-world
      image: local/hello-world:v1
      env:
        # ConfigMapから定義した値を環境変数として利用
        - name: env_key_1 
          valueFrom:
            configMapKeyRef:
              name: configmap-demo         
              key: env_key_1 
        - name: DIFFERENT_NAME
          valueFrom:
            configMapKeyRef:
              name: configmap-demo         
              key: env_key_2 
      volumeMounts:
      - name: config
        mountPath: "/config-test"
        readOnly: true
  volumes:
  # ファイルとして利用
  - name: config
    configMap:
      # Provide the name of the ConfigMap you want to mount.
      name: configmap-demo
      # An array of keys from the ConfigMap to create as files
      items:
      - key: "game.properties"
        path: "sub-path/game.properties"
      - key: "application.properties"
        path: "application.properties"