apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
type: Opaque
data:
  USER_NAME: "YWRtaW4=" # admin
  PASSWORD: "MWYyZDFlMmU2N2Rm" # 1f2d1e2e67df
  .secret-file: "dmFsdWUtMg0KDQo=" # value-2
stringData:
  TEXT: "not base64 data"
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  terminationGracePeriodSeconds: 3
  containers:
    - name: hello-world
      image: local/hello-world:v1
      env:
        - name: USER_NAME 
          valueFrom:
            secretKeyRef:
              key: USER_NAME
              name: secret-demo
        - name: PASSWORD 
          valueFrom:
            secretKeyRef:
              key: PASSWORD
              name: secret-demo
        - name: TEXT 
          valueFrom:
            secretKeyRef:
              key: TEXT
              name: secret-demo
      volumeMounts:
      - name: secret-demo-volume
        mountPath: "/secret-demo"
        readOnly: true
  volumes:
  - name: secret-demo-volume
    secret:
      secretName: secret-demo
      items:
        - key: .secret-file
          path: "sub/.secret-file"