apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      name: hello-world
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      terminationGracePeriodSeconds: 3
      containers:
      - name: hello-world
        image: local/hello-world:v1
        ports:
        - containerPort: 3000
      
