apiVersion: v1
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-01
provisioner: kubernetes.io/no-privisioner
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-class-01
  hostPath:
    path: /data/pv0001
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-001
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  storageClassName: storage-class-01
  volumeName: pv0001
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-1
  labels:
    app: hello-world-1
spec:
  terminationGracePeriodSeconds: 3
  containers:
  - name: hello-world-1
    image: local/hello-world:v1
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 3000
    volumeMounts: 
        - name: example-volume 
          mountPath: /var/www/html # 任意のパス 
  volumes: 
      - name: example-volume 
        persistentVolumeClaim: 
          claimName: pv-claim-001
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-2
  labels:
    app: hello-world-2
spec:
  terminationGracePeriodSeconds: 3
  containers:
  - name: hello-world-2
    image: local/hello-world:v1
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 3000
    volumeMounts: 
        - name: example-volume 
          mountPath: /var/www/html # 任意のパス 
  volumes: 
      - name: example-volume 
        persistentVolumeClaim: 
          claimName: pv-claim-001