apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  terminationGracePeriodSeconds: 3
  containers:
  - name: hello-world
    image: local/hello-world:v1
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 3000
