apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      terminationGracePeriodSeconds: 3
      affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                - key: disktype
                  operator: In
                  values:
                  - ssd
      containers:
      - name: hello-world
        image: local/hello-world:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

